version: '3'
services:
  db:
    build:
      context: docker/postgres
      network: host
    container_name: dejavu-db
    environment:
      - POSTGRES_DB=audio_recognition
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    networks:
      - db_network
    ports:
      - "5432:5432"
  python:
    build:
      context: docker/python
      network: host
    container_name: dejavu-app
    volumes:
      - .:/code
      - E:/docker_data/logs:/data/logs
      - E:/docker_data/files:/data/files
      - E:/docker_data/config:/data/config
    depends_on:
      - db
    networks:
      - db_network
    ports:
      - "8003:8000"
networks:
  db_network: