version: '3'
services:
  db:
    build:
      context: ./docker/postgres
      network: host
    environment:
      - POSTGRES_DB=dejavu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - db_network
    ports:
      - "5432:5432"
  python:
    build:
      context: ./docker/python
      network: host
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - db_network
networks:
  db_network: